# Generated by Django 5.1.6 on 2025-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symptomtracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chronic_illnesses",
            field=models.TextField(
                blank=True,
                help_text="List of chronic illnesses the user has been diagnosed with",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="medications",
            field=models.TextField(
                blank=True,
                help_text="List of medications the user is currently taking",
                null=True,
            ),
        ),
    ]
