# Generated by Django 5.1.6 on 2025-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symptomtracker", "0002_userprofile_chronic_illnesses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
